// Source:  https://github.com/shutterstock/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
//          http://www.youswear.com/index.asp?language=Hindi#.UYrh96JeauJ

using System.Collections.Generic;

namespace Noodle.Helpers
{
    /// <summary>
    /// Lists of bad words in major languages
    /// </summary>
    public class CensorWords
    {
        /// <summary>
        /// The hard stop words
        /// The '*' indicates a wildcard, or that the word can be a subword.
        /// </summary>
        public static List<string>  HardStopWords = new List<string>()
            {
                {"cunt"},
                {"fag"},
                {"fuck"},
                {"fucck"},
                {"fuk"},
                {"fuuck"},
                {"nigger"},
                {"penis"},
                {"poop"},
                {"shit"},
                {"shhit"},
                {"vagina"}
            };

        /// <summary>
        /// Language:  de
        /// </summary>
        public static List<string> De = new List<string>()
            {
                {"fick"},
                {"geil"},
                {"nackt"},
                {"onanieren"},
                {"vögeln"},
                {"wichser"},
                {"ficken"},
                {"arschloch"},
                {"möse"},
                {"arschficker"},
                {"hurensohn"},
                {"hure"},
                {"arsch"},
                {"arschlecker"},
                {"bumsen"},
                {"vögeln"},
                {"pimmel"},
                {"analritter"},
                {"titten"},
                {"möpse"},
                {"bratze"},
                {"dödel"},
                {"fratze"},
                {"poppen"},
                {"muschi"},
                {"mucke"},
                {"hackfresse"},
                {"wichsen"},
                {"ische"},
                {"latte"},
                {"kampflesbe"},
                {"kackbratze"},
                {"kacke"},
                {"scheiße"},
                {"kimme"},
                {"knackwurst"},
                {"nippel"},
                {"hupen"},
                {"milchtüten"},
                {"MILF"},
                {"morgenlatte"},
                {"mufti"},
                {"pimpern"},
                {"picheln"},
                {"pinkeln"},
                {"pissen"},
                {"kacken"},
                {"pisser"},
                {"porno"},
                {"popel"},
                {"reudig"},
                {"rosette"},
                {"lümmel"},
                {"flittchen"},
                {"schabracke"},
                {"schnackeln"},
                {"tittchen"},
                {"vollpfosten"}
            };

        /// <summary>
        /// Language:  en
        /// </summary>
        public static List<string> En = new List<string>()
            {
                {"2g1c"},
                {"2 girls 1 cup"},
                {"acrotomophilia"},
                {"anal"},
                {"anilingus"},
                {"anus"},
                {"arsehole"},
                {"ass"},
                {"asshole"},
                {"assmunch"},
                {"auto erotic"},
                {"autoerotic"},
                {"babeland"},
                {"baby batter"},
                {"ball gag"},
                {"ball gravy"},
                {"ball kicking"},
                {"ball licking"},
                {"ball sack"},
                {"ball sucking"},
                {"bangbros"},
                {"bareback"},
                {"barely legal"},
                {"barenaked"},
                {"bastardo"},
                {"bastinado"},
                {"bdsm"},
                {"beaver cleaver"},
                {"beaver lips"},
                {"bestiality"},
                {"bi curious"},
                {"big black"},
                {"big breasts"},
                {"big knockers"},
                {"big tits"},
                {"bimbos"},
                {"birdlock"},
                {"bitch"},
                {"black cock"},
                {"blonde action"},
                {"blonde on blonde action"},
                {"blow j"},
                {"blow your l"},
                {"blue waffle"},
                {"blumpkin"},
                {"bollocks"},
                {"bondage"},
                {"boner"},
                {"boners"},
                {"boob"},
                {"boobs"},
                {"booty call"},
                {"brown showers"},
                {"brunette action"},
                {"bukkake"},
                {"bulldyke"},
                {"bullet vibe"},
                {"bung hole"},
                {"bunghole"},
                {"busty"},
                {"butt"},
                {"butts"},
                {"buttcheeks"},
                {"butthole"},
                {"camel toe"},
                {"camgirl"},
                {"camslut"},
                {"camwhore"},
                {"carpet muncher"},
                {"carpetmuncher"},
                {"chink"},
                {"chocolate rosebuds"},
                {"circlejerk"},
                {"cleveland steamer"},
                {"clit"},
                {"clitoris"},
                {"clover clamps"},
                {"clusterfuck"},
                {"cock"},
                {"cocks"},
                {"coprolagnia"},
                {"coprophilia"},
                {"cornhole"},
                //{"cum"},
                {"cumming"},
                {"cunnilingus"},
                {"cunt"},
                {"darkie"},
                {"date rape"},
                {"daterape"},
                {"deep throat"},
                {"deepthroat"},
                {"dick"},
                {"dildo"},
                {"dirty pillows"},
                {"dirty sanchez"},
                {"dog style"},
                {"doggie style"},
                {"doggiestyle"},
                {"doggy style"},
                {"doggystyle"},
                {"dolcett"},
                {"domination"},
                {"dominatrix"},
                {"dommes"},
                {"donkey punch"},
                {"double dong"},
                {"double penetration"},
                {"dp action"},
                {"eat my ass"},
                {"ecchi"},
                {"ejaculation"},
                {"erotic"},
                {"erotism"},
                {"escort"},
                {"ethical slut"},
                {"eunuch"},
                {"fag"},
                {"fags"},
                {"faggot"},
                {"fecal"},
                {"felch"},
                {"fellatio"},
                {"feltch"},
                {"female squirting"},
                {"femdom"},
                {"figging"},
                {"fingering"},
                {"fisting"},
                {"foot fetish"},
                {"footjob"},
                {"frotting"},
                {"fuck"},
                {"fucck"},
                {"fuk"},
                {"fuuck"},
                {"fuck buttons"},
                {"fudge packer"},
                {"fudgepacker"},
                {"futanari"},
                {"g-spot"},
                {"gang bang"},
                {"gay sex"},
                {"genitals"},
                {"giant cock"},
                {"girl on"},
                {"girl on top"},
                {"girls gone wild"},
                {"goatcx"},
                {"goatse"},
                {"gokkun"},
                {"golden shower"},
                {"gook"},
                {"goo girl"},
                {"goodpoop"},
                {"goregasm"},
                {"grope"},
                {"group sex"},
                {"guro"},
                {"hand job"},
                {"handjob"},
                {"hard core"},
                {"hardcore"},
                {"hentai"},
                {"homoerotic"},
                {"honkey"},
                {"hooker"},
                {"hot chick"},
                {"how to kill"},
                {"how to murder"},
                {"huge fat"},
                {"humping"},
                {"incest"},
                {"intercourse"},
                {"jack off"},
                {"jail bait"},
                {"jailbait"},
                {"jerk off"},
                {"jigaboo"},
                {"jiggaboo"},
                {"jiggerboo"},
                {"jizz"},
                {"juggs"},
                {"kike"},
                {"kinbaku"},
                {"kinkster"},
                {"kinky"},
                {"knobbing"},
                {"leather restraint"},
                {"leather straight jacket"},
                {"lemon party"},
                {"lolita"},
                {"lovemaking"},
                {"make me come"},
                {"male squirting"},
                {"masturbate"},
                {"menage a trois"},
                {"milf"},
                {"missionary position"},
                {"motherfucker"},
                {"mound of venus"},
                {"mr hands"},
                {"muff diver"},
                {"muffdiving"},
                {"nambla"},
                {"nawashi"},
                {"negro"},
                {"neonazi"},
                {"nig nog"},
                {"nigga"},
                {"nigger"},
                {"niggers"},
                {"nimphomania"},
                {"nipple"},
                {"nipples"},
                {"nsfw images"},
                {"nude"},
                {"nudity"},
                {"nympho"},
                {"nymphomania"},
                {"octopussy"},
                {"omorashi"},
                {"one cup two girls"},
                {"one guy one jar"},
                {"orgasm"},
                {"orgy"},
                {"paedophile"},
                {"panties"},
                {"panty"},
                {"pedobear"},
                {"pedophile"},
                {"pegging"},
                {"penis"},
                {"phone sex"},
                {"piece of shit"},
                {"piss pig"},
                {"pissing"},
                {"pisspig"},
                {"playboy"},
                {"pleasure chest"},
                {"pole smoker"},
                {"ponyplay"},
                {"poof"},
                {"poop chute"},
                {"poopchute"},
                {"porn"},
                {"porno"},
                {"pornography"},
                {"prince albert piercing"},
                {"pthc"},
                {"pubes"},
                {"pussy"},
                {"queaf"},
                {"raghead"},
                {"raging boner"},
                {"rape"},
                {"raping"},
                {"rapist"},
                {"rectum"},
                {"reverse cowgirl"},
                {"rimjob"},
                {"rimming"},
                {"rosy palm"},
                {"rosy palm and her 5 sisters"},
                {"rusty trombone"},
                {"s&m"},
                {"sadism"},
                {"scat"},
                {"schlong"},
                {"scissoring"},
                {"semen"},
                {"sex"},
                {"sexo"},
                {"sexy"},
                {"shaved beaver"},
                {"shaved pussy"},
                {"shemale"},
                {"shibari"},
                {"shit"},
                {"shhit"},
                {"shitter"},
                {"shitting"},
                {"shithead"},
                {"shitface"},
                {"shota"},
                {"shrimping"},
                {"slanteye"},
                {"slut"},
                {"smut"},
                {"snatch"},
                {"snowballing"},
                {"sodomize"},
                {"sodomy"},
                {"spic"},
                {"spooge"},
                {"spread legs"},
                {"strap on"},
                {"strapon"},
                {"strappado"},
                {"strip club"},
                {"style doggy"},
                {"suck"},
                {"sucks"},
                {"suicide girls"},
                {"sultry women"},
                {"swastika"},
                {"swinger"},
                {"tainted love"},
                {"taste my"},
                {"tea bagging"},
                {"threesome"},
                {"throating"},
                {"tied up"},
                {"tight white"},
                {"tit"},
                {"tits"},
                {"titties"},
                {"titty"},
                {"tongue in a"},
                {"topless"},
                {"tosser"},
                {"towelhead"},
                {"tranny"},
                {"tribadism"},
                {"tub girl"},
                {"tubgirl"},
                {"tushy"},
                {"twat"},
                {"twink"},
                {"twinkie"},
                {"two girls one cup"},
                {"undressing"},
                {"upskirt"},
                {"urethra play"},
                {"urophilia"},
                {"vagina"},
                {"venus mound"},
                {"vibrator"},
                {"violet blue"},
                {"violet wand"},
                {"vorarephilia"},
                {"voyeur"},
                {"vagina"},
                {"vulva"},
                {"wank"},
                {"wet dream"},
                {"wetback"},
                {"white power"},
                {"women rapping"},
                {"wrapping men"},
                {"wrinkled starfish"},
                {"xx"},
                {"xxx"},
                {"yaoi"},
                {"yellow showers"},
                {"yiffy"},
                {"zoophilia"}
            };

        /// <summary>
        /// Language:  es
        /// </summary>
        public static List<string> Es = new List<string>()
            {
                {"asno"},
                {"bastardo"},
                {"concha"},
                {"infierno"},
                {"maldito"},
                {"martillo"},
                {"vete a la mierda"},
                {"Cabron"},
                {"Cabrón"},
                {"Follar"},
                {"Follador"},
                {"Gilipollas"},
                {"Gilipichis"},
                {"Hijoputa"},
                {"Hijo de puta"},
                {"Hijaputa"},
                {"Hija de puta"},
                {"Imbécil"},
                {"Idiota"},
                {"Jilipollas"},
                {"Kapullo"},
                {"Lameculos"},
                {"Maricón"},
                {"Marica"},
                {"Mariconazo"},
                {"Soplagaitas"},
                {"Soplapollas"},
                {"Verga"},
                {"Pinche"},
                {"Concha de tu madre"},
                {"Mierda"},
                {"Chupapollas"},
                {"Racista"},
                {"Haciendo el amor"},
                {"Pezón"},
                {"Fiesta de salchichas"},
                {"Puta"},
                {"Ramera"},
                {"Travesti"},
                {"Vulva"},
                {"Prostituta"},
                {"Sádico"},
                {"Pervertido"},
                {"Sexo"},
                {"Sexo oral"},
                {"Chupetón"},
                {"Heroína"},
                {"Drogas"},
                {"Trio"},
                {"Coprofagía"},
                {"Culo"},
                {"Pedo"},
                {"Esperma"},
                {"Semen"},
                {"Nazi"},
                {"Asesinato"},
                {"Pis"},
                {"Caca"},
                {"Tetas grandes"},
                {"Mamada"},
                {"Chupada"},
                {"Hacer una paja"},
                {"Coño"},
                {"Bollera"},
                {"Tía buena"},
                {"Maciza"},
                {"Macizorra"},
                {"Orina"}
            };

        /// <summary>
        /// Language:  fr
        /// </summary>
        public static List<string> Fr = new List<string>()
            {
                {"allumé"},
                {"allumée"},
                {"baiser"},
                {"bander"},
                {"bigornette"},
                {"bite"},
                {"bitte"},
                {"bloblos"},
                {"bordel"},
                {"bosser"},
                {"bourré"},
                {"bourrée"},
                {"branlage"},
                {"branler"},
                {"branlette"},
                {"branleur"},
                {"branleuse"},
                {"brouter le cresson"},
                {"caca"},
                {"cailler"},
                {"chatte"},
                {"chiasse"},
                {"chier"},
                {"chiottes"},
                {"cirer"},
                {"clito"},
                {"clitoris"},
                //{"con"},
                {"conne"},
                {"connard"},
                {"connasse"},
                {"couilles"},
                {"cramouille"},
                {"cul"},
                {"déconne"},
                {"déconner"},
                {"doudounes"},
                {"drague"},
                {"emmerdant"},
                {"emmerdeur"},
                {"emmerdeuse"},
                {"emmerder"},
                {"enculé"},
                {"enculée"},
                {"enfoiré"},
                {"enfoirée"},
                {"étron"},
                {"fils de pute"},
                {"fille de pute"},
                {"flic"},
                {"folle"},
                {"foutre"},
                {"gerber"},
                {"gouine"},
                {"grande folle"},
                {"grogniasse"},
                {"gueule"},
                {"jouir"},
                {"la putain de ta mère"},
                {"MALPT"},
                {"maquereau"},
                {"melon"},
                {"ménage a trois"},
                {"merde"},
                {"merdeuse"},
                {"merdeux"},
                {"merlan"},
                {"meuf"},
                {"morue"},
                {"moule"},
                {"nègre"},
                {"nique ta mère"},
                {"noune"},
                {"palucher"},
                {"pédale"},
                {"pédé"},
                {"péter"},
                {"pipe"},
                {"pipi"},
                {"pisser"},
                {"poilu"},
                {"pouffiasse"},
                {"pousse-crotte"},
                {"putain"},
                {"pute"},
                {"queue"},
                {"ramoner"},
                {"salaud"},
                {"salope"},
                {"serin"},
                {"service trois pièces"},
                {"suce"},
                {"tante"},
                {"tapette"},
                {"teuf"},
                {"tirer"},
                {"trick"},
                {"tringle"},
                {"tringler"},
                {"trique"},
                {"trou du cul"},
                {"turlute"},
                {"veuve"},
                {"viande a pneus"}
            };

        public static List<string> Hi = new List<string>()
            {
                {"Aand mat kaha"},
                {"Baap ke lavde"},
                {"Bakrichod"},
                {"Betichod"},
                {"Bhai Chhod bhayee chod"},
                {"Bhen Chhod bhaynchod"},
                {"Bhen ke lode"},
                {"Cha Cha Chod"},
                {"Chod ke bal ka kida"},
                {"Chopre he randi"},
                {"Chudasi"},
                {"Chut ka maindak"},
                {"Chutia"},
                {"Chutiya chootia"},
                {"Dheeli Choot"},
                {"Gaand chaat mera"},
                {"Gaand gaand"},
                {"Gaand ke Dhakan"},
                {"Gaandu"},
                {"Gandi Chut mein Sadta hua ganda kida"},
                {"Gandmasti"},
                {"Jhaat ke baal"},
                {"Jhat lahergaya"},
                {"Jhatoo"},
                {"Kukarchod"},
                {"Kutha Sala"},
                {"Lode jesi shakal ke"},
                {"Lode ke baal"},
                {"Lund chuse"},
                {"Lund luhnd"},
                {"Madar Chod"},
                {"Madarchod ke Aulaad"},
                {"Mai Chod"},
                {"Mera mume le"},
                {"Mere fudi kha ley"},
                {"Meri ghand ka baal"},
                {"Sust Lund ki padaish"},
                {"Tatti Ander Lele"},
                {"Tere Baap Ki Gaand"},
                {"Teri Chute Mai Chuglee"},
                {"Teri Maa ki sukhi bhos"},
                {"Teri bhosri mein aag"},
                {"Teri gaand me danda"},
                {"Teri maa ke bhosade ke baal"},
                {"Tharki"},
                {"bhadwe ki nasal"},
                {"bhen ke lode maa chuda"},
                {"bhosadi ke"},
                {"bhosdee kay"},
                {"bhosdi k"},
                {"bhundi"},
                {"bulle ke baal"},
                {"camina"},
                {"chod"},
                {"chod bhangra"},
                {"choot ka paani"},
                {"choot ka pissu"},
                {"chootia"},
                {"chut ke makkhan"},
                {"chutiya"},
                {"dalli"},
                {"gaand maar bhen chod"},
                {"gaandu"},
                {"goli"},
                {"haram zaadaa"},
                {"harami"},
                {"jhaat"},
                {"kaala lund"},
                {"kaali kutti"},
                {"kuthri"},
                {"kutte"},
                {"lavde ka baal"},
                {"lowde ka bal"},
                {"lund"},
                {"maa-cho"},
                {"maal chhodna"},
                {"mahder chod"},
                {"mera gota moo may lay"},
                {"moo may lay mera"},
                {"padosi ke calender"},
                {"padosi ki aulaad"},
                {"rand ki moot"},
                {"randi baj"},
                {"randi ka larka"},
                {"randi ke bacche"},
                {"randi ke beej"},
                {"saale lm"},
                {"sab ka lund teri ma ki chut mein"},
                {"sala/sale"},
                {"sinak se paida hua"},
                {"suvar chod"},
                {"suwar ki aulad"},
                {"tagad"},
                {"tera gittha"},
                {"tere maa ka bur"},
                {"teri maa ka bhosra"},
                {"teri maa ki choot me kutte ka lavda"},
                {"teri maa ki chut"},
                {"teri maa ki chute"}
            };

        /// <summary>
        /// Language: It
        /// </summary>
        public static List<string> It = new List<string>()
            {
                {"allupato"},
                {"ammucchiata"},
                {"anale"},
                {"arrapato"},
                {"arrusa"},
                {"arruso"},
                {"assatanato"},
                {"bagascia"},
                {"bagnarsi"},
                {"baldracca"},
                {"balle"},
                {"battere"},
                {"battona"},
                {"belino"},
                {"biga"},
                {"bocchinara"},
                {"bocchino"},
                {"bofilo"},
                {"boiata"},
                {"bordello"},
                {"brinca"},
                {"bucaiolo"},
                {"budiùlo"},
                {"buona donna"},
                {"busone"},
                {"cacca"},
                {"caccati in mano e prenditi a schiaffi"},
                {"caciocappella"},
                {"cadavere"},
                {"cagare"},
                {"cagata"},
                {"cagna"},
                {"cammello"},
                {"cappella"},
                {"carciofo"},
                {"carità"},
                {"casci"},
                {"cazzata"},
                {"cazzimma"},
                {"cazzo"},
                {"checca"},
                {"chiappa"},
                {"chiavare"},
                {"chiavata"},
                {"ciospo"},
                {"ciucciami il cazzo"},
                {"coglione"},
                {"coglioni"},
                {"cornuto"},
                {"cozza"},
                {"culattina"},
                {"culattone"},
                {"culo"},
                {"di merda"},
                {"ditalino"},
                {"duro"},
                {"fare unaŠ"},
                {"fava"},
                {"femminuccia"},
                {"fica"},
                {"figa"},
                {"figlio di buona donna"},
                {"figlio di puttana"},
                {"figone"},
                {"finocchio"},
                {"fottere"},
                {"fottersi"},
                {"fracicone"},
                {"fregna"},
                {"frocio"},
                {"froscio"},
                {"fuori come un balcone"},
                {"goldone"},
                {"grilletto"},
                {"guanto"},
                {"guardone"},
                {"incazzarsi"},
                {"incoglionirsi"},
                {"ingoio"},
                {"l'arte bolognese"},
                {"leccaculo"},
                {"lecchino"},
                {"lofare"},
                {"loffa"},
                {"loffare"},
                {"lumaca"},
                {"manico"},
                {"mannaggia"},
                {"merda"},
                {"merdata"},
                {"merdoso"},
                {"mignotta"},
                {"minchia"},
                {"minchione"},
                {"mona"},
                {"monta"},
                {"montare"},
                {"mussa"},
                {"nave scuola"},
                {"nerchia"},
                {"nudo"},
                {"padulo"},
                {"palle"},
                {"palloso"},
                {"patacca"},
                {"patonza"},
                {"pecorina"},
                {"pesce"},
                {"picio"},
                {"pincare"},
                {"pipa"},
                {"pippone"},
                {"pipì"},
                {"pirla"},
                {"pisciare"},
                {"piscio"},
                {"pisello"},
                {"pistola"},
                {"pistolotto"},
                {"pomiciare"},
                {"pompa"},
                {"pompino"},
                {"porca"},
                {"porca madonna"},
                {"porca miseria"},
                {"porca puttana"},
                {"porco due"},
                {"porco zio"},
                {"potta"},
                {"puttana"},
                {"quaglia"},
                {"recchione"},
                {"regina"},
                {"rincoglionire"},
                {"rizzarsi"},
                {"rompiballe"},
                {"ruffiano"},
                {"sbattere"},
                {"sbattersi"},
                {"sborra"},
                {"sborrata"},
                {"sborrone"},
                {"sbrodolata"},
                {"scopare"},
                {"scopata"},
                {"scorreggiare"},
                {"sega"},
                {"slinguare"},
                {"slinguata"},
                {"smandrappata"},
                {"soccia"},
                {"socmel"},
                {"sorca"},
                {"spagnola"},
                {"spompinare"},
                {"sticchio"},
                {"stronza"},
                {"stronzata"},
                {"stronzo"},
                {"sveltina"},
                {"sverginare"},
                {"tarzanello"},
                {"terrone"},
                {"testa di cazzo"},
                {"tette"},
                {"tirare"},
                {"topa"},
                {"troia"},
                {"trombare"},
                {"uccello"},
                {"vacca"},
                {"vaffanculo"},
                {"vangare"},
                {"venire"},
                {"zinne"},
                {"zio cantante"},
                {"zoccola"}
            };

        /// <summary>
        /// Language:  ja
        /// </summary>
        public static List<string> Ja = new List<string>()
            {
                {"g スポット"},
                {"s ＆ m"},
                {"sm女王"},
                {"xx"},
                {"いたずら"},
                {"おしっこ"},
                {"おしり"},
                {"おしりのあな"},
                {"おっぱい"},
                {"おもらし"},
                {"お尻"},
                {"しばり"},
                {"ちんこ"},
                {"なめ"},
                {"ふたなり"},
                {"ぶっかけ"},
                {"ぽっちゃり"},
                {"まんこ"},
                {"やおい"},
                {"やりまん"},
                {"アジアのかわいい女の子"},
                {"アスホール"},
                {"アナリングス"},
                {"アナル"},
                {"イラマチオ"},
                {"ウェブカメラ"},
                {"エクスタシー"},
                {"エスコート"},
                {"エッチ"},
                {"エロティズム"},
                {"エロティック"},
                {"オカマ"},
                {"オシリ"},
                {"オッパイ"},
                {"オナニー"},
                {"オマンコ"},
                {"オーガズム"},
                {"カント"},
                {"カーマスートラ"},
                {"クリトリス"},
                {"クンニリングス"},
                {"グループ・セックス"},
                {"グロ"},
                {"ゲイの男性"},
                {"ゲイボーイ"},
                {"ゲイ・セックス"},
                {"コカイン"},
                {"ゴックン"},
                {"ゴールデンシャワー"},
                {"サディズム"},
                {"スウィンガー"},
                {"スカトロ"},
                {"スカートの中"},
                {"ストラップオン"},
                {"ストリップ劇場"},
                {"スラット"},
                {"スリット"},
                {"セクシーな"},
                {"セクシーな 10 代"},
                {"セックス"},
                {"ソドミー"},
                {"テレフォンセックス"},
                {"ディック"},
                {"ディルド"},
                {"ディープ・スロート"},
                {"デブ"},
                {"デートレイプ"},
                {"トップレス"},
                {"ドッグスタイル"},
                {"ニガー"},
                {"ヌード"},
                {"ネオ・ナチ"},
                {"ハードコア"},
                {"バイブレーター"},
                {"バック・スタイル"},
                {"パイパン"},
                {"パンティー"},
                {"ビッチ"},
                {"ファック"},
                {"ファンタジー"},
                {"フィスト"},
                {"フェティッシュ"},
                {"フェラチオ"},
                {"フック"},
                {"プリンス アルバート ピアス"},
                {"プレイボーイ"},
                {"ベアバック"},
                {"ペニス"},
                {"ペニスバンド"},
                {"ホモ"},
                {"ボンテージ"},
                {"ボーイズラブ"},
                {"ボールを蹴る"},
                {"ボールギャグ"},
                {"ポルノ"},
                {"ポルノグラフィー"},
                {"マザー・ファッカー"},
                {"マスターベーション"},
                {"ユダヤ人"},
                {"ラティーナ"},
                {"ラバー"},
                {"ランジェリー"},
                {"レイプ"},
                {"レズビアン"},
                {"ロリータ"},
                {"ローター"},
                {"両刀"},
                {"両性"},
                {"両性具有"},
                {"中出し"},
                {"乱交"},
                {"乳首"},
                {"二穴"},
                {"人妻"},
                {"人種"},
                {"児童性虐待"},
                {"剃毛"},
                {"勃起する"},
                {"卍"},
                {"合意の性交"},
                {"噴出"},
                {"売春婦"},
                {"変態"},
                {"夢精"},
                {"大陰唇"},
                {"女の子"},
                {"女子高生"},
                {"女王様"},
                {"女装"},
                {"奴隷"},
                {"嫌い"},
                {"宦官"},
                {"射精"},
                {"尿道プレイ"},
                {"巨乳"},
                {"巨根"},
                {"平手打ち"},
                {"幼児"},
                {"幼児性愛者"},
                {"強姦犯"},
                {"後背位"},
                {"性交"},
                {"手コキ"},
                {"拷問"},
                {"挿入"},
                {"支配"},
                {"新しいポルノ"},
                {"正常位"},
                {"殺し方"},
                {"殺人事件"},
                {"殺人方法"},
                {"毛深い"},
                {"淫乱"},
                {"潮吹き女"},
                {"潮吹き男性"},
                {"獣姦"},
                {"玉なめ"},
                {"玉舐め"},
                {"生殖器"},
                {"直腸"},
                {"精液"},
                {"糞"},
                {"糞便"},
                {"糞尿愛好症"},
                {"緊縛"},
                {"縛り"},
                {"肛門"},
                {"脱衣"},
                {"膣"},
                {"自己愛性"},
                {"茶色のシャワー"},
                {"裸"},
                {"裸の女性"},
                {"覗き"},
                {"誘惑"},
                {"貞操帯"},
                {"足を広げる"},
                {"足フェチ"},
                {"輪姦"},
                {"近親相姦"},
                {"陰毛"},
                {"革抑制"},
                {"騎上位"},
                {"黒人"}
            };

        /// <summary>
        /// Language:  nl
        /// </summary>
        public static List<string> Nl = new List<string>()
            {
                {"aardappels afgieteng"},
                {"achter het raam zitten"},
                {"afberen"},
                {"aflebberen"},
                {"afrossen"},
                {"afrukken"},
                {"aftrekken"},
                {"afwerkplaats"},
                {"afzeiken"},
                {"afzuigen"},
                {"anderhalve man en een paardekop"},
                {"asbak"},
                {"aso"},
                {"bagger schijten"},
                {"balen"},
                {"bedonderen"},
                {"befborstelg"},
                {"beffen"},
                {"bekken"},
                {"belazeren"},
                {"besodemieterd zijn"},
                {"besodemieteren"},
                {"beurt"},
                {"boemelen"},
                {"boerelul"},
                {"boerenpummelg"},
                {"bokkelul"},
                {"botergeil"},
                {"broekhoesten"},
                {"brugpieperg"},
                {"buffelen"},
                {"buiten de pot piesen"},
                {"da's kloten van de bok"},
                {"de ballen"},
                {"de hoer spelen"},
                {"de hond uitlaten"},
                {"de koffer induiken"},
                {"de pijp aan maarten geven"},
                {"de pijp uitgaan"},
                {"delg"},
                {"dombo"},
                {"draaikontg"},
                {"driehoog achter wonen"},
                {"drolg"},
                {"drooggeiler"},
                {"droogkloot"},
                {"een beurt geven"},
                {"een nummertje maken"},
                {"een wip maken"},
                {"eikel"},
                {"engerd"},
                {"flamoes"},
                {"flikken"},
                {"flikker"},
                {"gadverdamme"},
                {"galbak"},
                {"gat"},
                {"gedoogzone"},
                {"geilneef"},
                {"gesodemieter"},
                {"godverdomme"},
                {"graftak"},
                {"gras maaien"},
                {"gratenkutg"},
                {"greppeldel"},
                {"griet"},
                {"hoempert"},
                {"hoer"},
                {"hoerenbuurt"},
                {"hoerenloper"},
                {"hoerig"},
                {"hol"},
                {"hufter"},
                {"huisdealer"},
                {"johny"},
                {"kanen"},
                {"kettingzeugg"},
                {"klaarkomen"},
                {"klerebeer"},
                {"klojo"},
                {"klooien"},
                {"klootjesvolk"},
                {"klootoog"},
                {"klootzak"},
                {"kloten"},
                {"knor"},
                {"kontg"},
                {"kontneuken"},
                {"krentekakker"},
                {"kut"},
                {"kuttelikkertje"},
                {"kwakkieg"},
                {"liefdesgrot"},
                {"lul"},
                {"lul-de-behanger"},
                {"lulhannes"},
                {"lummel"},
                {"mafketel"},
                {"matennaaierg"},
                {"matje"},
                {"mof"},
                {"mutsg"},
                {"naaien"},
                {"naakt"},
                {"neuken"},
                {"neukstier"},
                {"nicht"},
                {"oetlul"},
                {"op z'n hondjes"},
                {"op z'n sodemieter geven"},
                {"opgeilen"},
                {"opkankeren"},
                {"oprotten"},
                {"opsodemieteren"},
                {"opzouten"},
                {"ouwe rukker"},
                {"ouwehoer"},
                {"ouwehoeren"},
                {"paal"},
                {"paardelul"},
                {"palen"},
                {"penozeg"},
                {"piesen"},
                {"pijpbekkieg"},
                {"pijpen"},
                {"pik"},
                {"pleurislaaier"},
                {"poep"},
                {"poepen"},
                {"poot"},
                {"portiekslet"},
                //{"pot"},
                {"potverdorie"},
                {"publiciteitsgeil"},
                {"raaskallen"},
                {"reet"},
                {"reet trappen, voor zijn"},
                {"reetridder"},
                {"remsporeng"},
                {"reutelen"},
                {"rothoer"},
                {"rotzak"},
                {"rukhond"},
                {"rukken"},
                {"schatje"},
                {"schijt"},
                {"schijten"},
                {"schoft"},
                {"schuinsmarcheerder"},
                {"shit"},
                {"slempen"},
                {"sletg"},
                {"sletterig"},
                {"slik mijn zaad"},
                {"snolg"},
                {"spuiten"},
                {"standje"},
                {"standje-69g"},
                {"stoephoer"},
                {"stootje"},
                {"strontg"},
                {"sufferdg"},
                {"tapijtnek"},
                {"teefg"},
                {"temeier"},
                {"teringlijer"},
                {"toeter"},
                {"tongzoeng"},
                {"triootjeg"},
                {"trottoir prostituée"},
                {"trottoirteef"},
                {"utrecht"},
                {"vergallen"},
                {"verkloten"},
                {"verneuken"},
                {"viespeuk"},
                {"vingeren"},
                {"vleesroos"},
                {"voor jan lul"},
                {"voor jan-met-de-korte-achternaam"},
                {"watje"},
                {"welzijnsmafia"},
                {"wijf"},
                {"wippen"},
                {"wuftje"},
                {"zaadje"},
                {"zakkenwasser"},
                {"zeiken"},
                {"zeiker"},
                {"zuigen"},
                {"zuiplap"}
            };

        /// <summary>
        /// Language:  pt
        /// </summary>
        public static List<string> Pt = new List<string>()
            {
                {"aborto"},
                {"amador"},
                {"aranha"},
                {"ariano"},
                {"balalao"},
                {"bastardo"},
                {"bicha"},
                {"biscate"},
                {"bissexual"},
                {"boceta"},
                {"boob"},
                {"bosta"},
                {"braulio de borracha"},
                {"bumbum"},
                {"burro"},
                {"cabrao"},
                {"cacete"},
                {"cagar"},
                {"camisinha"},
                {"caralho"},
                {"cerveja"},
                {"chochota"},
                {"chupar"},
                {"clitoris"},
                {"cocaína"},
                {"colhoes"},
                {"comer"},
                {"cona"},
                {"consolo"},
                {"corno"},
                {"dar o rabo"},
                {"dum raio"},
                {"esporra"},
                {"fecal"},
                {"filho da puta"},
                {"foda"},
                {"foda-se"},
                {"foder"},
                {"frango assado"},
                {"gozar"},
                {"grelho"},
                {"heroína"},
                {"heterosexual"},
                {"homem gay"},
                {"homoerótico"},
                {"homosexual"},
                {"inferno"},
                {"lolita"},
                {"lésbica"},
                {"merda"},
                {"paneleiro"},
                {"passar um cheque"},
                {"pau"},
                {"peidar"},
                {"porra"},
                {"puta"},
                {"puta que pariu"},
                {"puta que te pariu"},
                {"pênis"},
                {"queca"},
                {"sacanagem"},
                {"saco"},
                {"torneira"},
                {"transar"},
                {"vai tomar no cu"},
                {"vai-te foder"},
                {"veado"},
                {"vibrador"},
                {"xana"},
                {"xochota"},
                {"ânus"}
            };

        /// <summary>
        /// Language:  ru
        /// </summary>
        public static List<string> Ru = new List<string>()
            {
                {"bychara"},
                {"byk"},
                {"chernozhopyi"},
                {"dolboy'eb"},
                {"ebalnik"},
                {"ebalo"},
                {"ebalom sch'elkat"},
                {"gol"},
                {"mudack"},
                {"opizdenet"},
                {"osto'eblo"},
                {"ostokhuitel'no"},
                {"ot'ebis"},
                {"otmudohat"},
                {"otpizdit"},
                {"otsosi"},
                {"padlo"},
                {"pedik"},
                {"perdet"},
                {"petuh"},
                {"pidar gnoinyj"},
                {"piz'det"},
                {"piz`dyulina"},
                {"pizd'uk"},
                {"pizda"},
                {"pizdato"},
                {"pizdatyi"},
                {"pizdetc"},
                {"pizdoi nakryt'sja"},
                {"po khuy"},
                {"po'imat' na konchik"},
                {"po'iti posrat"},
                {"podi ku'evo"},
                {"poeben"},
                {"poluchit pizdy"},
                {"pososi moyu konfetku"},
                {"prissat"},
                {"proebat"},
                {"promudobl'adsksya pizdopro'ebina"},
                {"propezdoloch"},
                {"prosrat"},
                {"raspeezdeyi"},
                {"raspizdatyi"},
                {"raz'yebuy"},
                {"raz'yoba"},
                {"s'ebat'sya"},
                {"shalava"},
                {"styervo"},
                {"sukin syn"},
                {"svodit posrat"},
                {"svoloch"},
                {"trakhat'sya"},
                {"trimandoblydskiy pizdoproyob"},
                {"u'ebitsche"},
                {"ubl'yudok"},
                {"uboy"},
                {"v pizdu"},
                {"vafl'a"},
                {"vafli lovit"},
                {"vyperdysh"},
                {"vzdrochennyi"},
                {"yeb vas"},
                {"za'ebat"},
                {"zaebis"},
                {"zalupa"},
                {"zalupat"},
                {"zasranetc"},
                {"zassat"},
                {"zlo'ebuchy"},
                {"бардак"},
                {"бздёнок"},
                {"блядки"},
                {"блядовать"},
                {"блядство"},
                {"блядь"},
                {"бугор"},
                {"во пизду"},
                {"встать раком"},
                {"выёбываться"},
                {"гандон"},
                {"говно"},
                {"говнюк"},
                {"голый"},
                {"дать пизды"},
                {"дерьмо"},
                {"дрочить"},
                {"другой дразнится"},
                {"ебать"},
                {"ебать-копать"},
                {"ебло"},
                {"ебнуть"},
                {"жопа"},
                {"жополиз"},
                {"играть на кожаной флейте"},
                {"измудохать"},
                {"каждый дрочит как он хочет"},
                {"как два пальца обоссать"},
                {"какая разница"},
                {"курите мою трубку"},
                {"лысого в кулаке гонять"},
                {"малофя"},
                {"манда"},
                {"мандавошка"},
                {"мент"},
                {"муда"},
                {"мудило"},
                {"мудозмон"},
                {"на фиг"},
                {"на хуй"},
                {"на хую вертеть"},
                {"на хуя"},
                {"наебать"},
                {"наебениться"},
                {"наебнуться"},
                {"нахуячиться"},
                {"не ебет"},
                {"невебенный"},
                {"ни за хуй собачу"},
                {"ни хуя"},
                {"обнаженный"},
                {"обоссаться можно"},
                {"один ебётся"},
                {"опесдол"},
                {"офигеть"},
                {"охуеть"},
                {"охуйтельно"},
                {"половое сношение"},
                {"секс"},
                {"сиски"},
                {"спиздить"},
                {"срать"},
                {"ссать"},
                {"траxать"},
                {"ты мне ваньку не валяй"},
                {"фига"},
                {"хапать"},
                {"хер с ней"},
                {"хер с ним"},
                {"хохол"},
                {"хрен"},
                {"хуем груши околачивать"},
                {"хуеплет"},
                {"хуило"},
                {"хуиней страдать"},
                {"хуиня"},
                {"хуй"},
                {"хуй пинать"},
                {"хуйнуть"},
                {"хуёво"},
                {"хуёвый"},
                {"ёб твою мать"},
                {"ёбарь"}
            };

        /// <summary>
        /// Language:  zh
        /// </summary>
        public static List<string> Zh = new List<string>()
            {
                {"成人"},
                {"处女"},
                {"口交"},
                {"迷药"},
                {"性爱"},
                {"性器"},
                {"阴茎"},
                {"淫乱"},
                {"性交"},
                {"激情"},
                {"九游"},
                {"私服"},
                {"扒光"},
                {"白痴"},
                {"白癡"},
                {"白烂"},
                {"包皮"},
                {"笨蛋"},
                {"色情"},
                {"情色"},
                {"嫖娼"},
                {"卖淫"},
                {"淫秽"},
                {"屄"},
                {"逼"},
                {"逼样"},
                {"婊子"},
                {"婊子养的"},
                {"操机掰"},
                {"操妳"},
                {"操妳妈"},
                {"操妳娘"},
                {"操妳全家"},
                {"操妳祖宗"},
                {"操你全家"},
                {"操你祖宗"},
                {"懆您妈"},
                {"懆您娘"},
                {"肏"},
                {"插你"},
                {"插死你"},
                {"吃屎"},
                {"吹箫"},
                {"打炮"},
                {"荡妇"},
                {"屌"},
                {"放荡"},
                {"肥西"},
                {"干x娘"},
                {"干机掰"},
                {"干妳老母"},
                {"干妳妈"},
                {"干妳马"},
                {"干妳娘"},
                {"干你老母"},
                {"干你良"},
                {"干你娘"},
                {"干您娘"},
                {"干七八"},
                {"干死CS"},
                {"干死GM"},
                {"干死客服"},
                {"干死你"},
                {"幹"},
                {"赣您娘"},
                {"灨你娘"},
                {"狗狼养的"},
                {"狗屁"},
                {"龟儿子"},
                {"龟头"},
                {"鬼公"},
                {"花柳"},
                {"机八"},
                {"机巴"},
                {"机机歪歪"},
                {"鸡8"},
                {"鸡八"},
                {"鸡叭"},
                {"鸡吧"},
                {"鸡芭"},
                {"鸡鸡"},
                {"鸡奸"},
                {"雞巴"},
                {"几八"},
                {"几巴"},
                {"几叭"},
                {"几芭"},
                {"妓"},
                {"妓女"},
                {"妓院"},
                {"奸"},
                {"奸你"},
                {"姦"},
                {"贱B"},
                {"贱货"},
                {"贱人"},
                {"賤"},
                {"交配"},
                {"姣西"},
                {"叫床"},
                {"她马的"},
                {"军妓"},
                {"靠爸"},
                {"靠北"},
                {"靠背"},
                {"靠母"},
                {"靠腰"},
                {"口肯"},
                {"懒8"},
                {"懒八"},
                {"懒叫"},
                {"懒教"},
                {"烂逼"},
                {"烂货"},
                {"爛"},
                {"浪叫"},
                {"老二"},
                {"老母"},
                {"老味"},
                {"轮奸"},
                {"妈B"},
                {"妈逼"},
                {"妈比"},
                {"妈的"},
                {"妈的B"},
                {"妈个B"},
                {"妈妈的"},
                {"卖B"},
                {"卖比"},
                {"淫荡"},
                {"淫妇"},
                {"淫西"},
                {"奶子"},
                {"妳她妈的"},
                {"妳老母的"},
                {"妳妈的"},
                {"妳马的"},
                {"妳娘的"},
                {"你她马的"},
                {"你妈"},
                {"你妈的"},
                {"你马的"},
                {"你娘"},
                {"你娘卡好"},
                {"你娘咧"},
                {"你全家"},
                {"你是鸡"},
                {"你是鸭"},
                {"你他马的"},
                {"你它妈的"},
                {"你它马的"},
                {"屁股"},
                {"月经"},
                {"杂种"},
                {"祖宗"},
                {"做爱"},
                {"嫖客"},
                {"姘头"},
                {"仆街"},
                {"强奸你"},
                {"日你"},
                {"日他娘"},
                {"乳头"},
                {"撒尿"},
                {"塞你爸"},
                {"塞你公"},
                {"塞你老母"},
                {"塞你老师"},
                {"塞你母"},
                {"塞你娘"},
                {"赛妳阿母"},
                {"赛你老母"},
                {"三级片"},
                {"骚逼"},
                {"驶你爸"},
                {"驶你公"},
                {"驶你老母"},
                {"驶你老师"},
                {"驶你母"},
                {"驶你娘"},
                {"傻比"},
                {"射精"},
                {"射你"},
                {"他妈"},
                {"他妈ㄉ王八蛋"},
                {"他马的"},
                {"他奶娘的"},
                {"他娘"},
                {"他奶奶的"},
                {"他奶奶"},
                {"外阴"},
                {"王八蛋"},
                {"下贱"},
                {"下三烂"},
                {"性爱"},
                {"性交"},
                {"性无能"},
                {"阳具"},
                {"阳萎"},
                {"野鸡"},
                {"性"},
                {"阴唇"},
                {"阴毛"},
                {"招妓"},
                {"小鸡鸡"},
                {"小鸡巴"},
                {"大鸡巴"},
                {"卵"},
                {"精子"},
                {"卵子"},
                {"大卵子"},
                {"大卵泡"},
                {"小卵子"},
                {"小卵泡"},
                {"阴茎"},
                {"阴道"},
                {"阴部"},
                {"屁眼"},
                {"奶"},
                {"妈个比"},
                {"妈个老比"},
                {"强奸"},
                {"淫"},
                {"淫棍"},
                {"乳房"},
                {"乳"},
                {"瘪三"},
                {"刚瘪三"},
                {"小瘪三"},
                {"老瘪三"},
                {"十三点"},
                {"13点"},
                {"刚度"},
                {"册那"},
                {"小乳头"},
                {"鸡巴"},
                {"阴户"},
                {"湿透的内裤"},
                {"肉缝"},
                {"肉棒"},
                {"淫水"},
                {"肉壁"},
                {"肉棍子"},
                {"口交"},
                {"肛交"},
                {"小肉粒"},
                {"阴核"},
                {"巨乳"},
                {"日你妈"},
                {"日你老母"},
                {"日你老娘"},
                {"日批"},
                {"干你妈"},
                {"你奶奶的"},
                {"贼你妈"},
                {"操你"},
                {"操你妈"},
                {"操你娘"},
                {"操你奶奶"},
                {"操你老母"},
                {"操你老妈"},
                {"娘的"},
                {"娘个比"},
                {"他妈的"},
                {"她妈的"},
                {"它妈的"},
                {"他妈地"},
                {"她妈地"},
                {"它妈地"},
                {"我操你祖宗十八代"},
                {"奶奶的熊"},
                {"你个傻比"},
                {"个老子的"},
                {"骚货"},
                {"骚比"},
                {"小骚货"},
                {"小骚比"},
                {"老骚货"},
                {"老骚比"},
                {"瓜娃子"},
                {"瓜婆娘"},
                {"瓜批"},
                {"干你"},
                {"操比"},
                {"操逼"},
                {"后庭"},
                {"双峰微颤"},
                {"贝肉"},
                {"玉杵"},
                {"密洞"},
                {"抽插"},
                {"乳波臀浪"},
                {"乳交"},
                {"打飞机"},
                {"傻逼"},
                {"想上你"},
                {"狗日"}
            };
    }
}